<?php
# This file was automatically generated by the MediaWiki 1.20.5
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "HTC-as-a-Service, KISTI";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/htcwiki";
$wgScriptExtension  = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://htcaas.kisti.re.kr";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgScriptPath/images/htcaas.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "htcaas-admin@kisti.re.kr";
$wgPasswordSender   = "htcaas-admin@kisti.re.kr";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

############
#$wgReadOnly = "In progress";

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
#$wgDBname           = "mediawiki";
$wgDBname           = "htcwikidb";  //the htcaas_wiki database name created in mysql
$wgDBuser           = "root";
$wgDBpassword       = "htcaas";
# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageResize = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
# be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php

$wgLanguageCode = "en";

$wgSecretKey = "3cd33ecb65644cb20e991e47c3a8c09a6356f273f0f00185ffdc5f9341d9eabb";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "4feb122196bd25ee";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;

# End of automatically generated settings.
# Add more configuration options below.


# Enable HTML code
$wgRawHtml = true;

require_once("$IP/extensions/WikiCategoryTagCloud/WikiCategoryTagCloud.php"); 
# Wiki Category Tag Cloud extension


##Language setting

# Restrict editing by all non-sysop users
$wgGroupPermissions['*']['edit']=false;
$wgGroupPermissions['user']['edit'] = false;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['importupload'] = true;

require_once("$IP/extensions/AddThis/AddThis.php");
unset($wgAddThisSBServ[0]);
unset($wgAddThisSBServ[4]);
unset($wgAddThisHServ[0]);
unset($wgAddThisHServ[1]);
unset($wgAddThisHServ[2]);
unset($wgAddThisHServ[3]);
unset($wgAddThisHServ[4]);
unset($wgAddThisHServ[5]);
unset($wgAddThisHServ[6]);
unset($wgAddThisHServ[7]);


$wgFileExtensions[] = 'zip';
$wgFileExtensions[] = 'doc';
$wgFileExtensions[] = 'ppt';
$wgFileExtensions[] = 'pdf';
$wgFileExtensions[] = 'xlsx';
$wgFileExtensions[] = 'pptx';
$wgFileExtensions[] = 'swf';
$wgFileExtensions[] = 'hwp';
$wgFileExtensions[] = 'docx';
$wgFileExtensions[] = 'xlsx';
$wgFileExtensions[] = 'jpeg';
$wgFileExtensions[] = 'py';
$wgFileExtensions = array(
    'png', 'gif', 'jpg', 'jpeg', 'pptx', 'ppt', 'pdf', 'doc', 'docx',
    'mp3', 'py', 'xls', 'xlsx', 'swf', 'hwp', 'zip', 'tar.gz', 'py'
    );

#$wgStrictFileExtensions = false;

require_once("$IP/extensions/Babel/Babel.php");
#require_once("$IP/extensions/SNSButtonsInSidebar/SNSButtonsInSidebar.php");

# add favicon
$wgFavicon = "$wgScriptPath/icon2.ico";

require_once("$IP/extensions/WikiEditor/WikiEditor.php");
# Enables use of WikiEditor by default but still allow users to disable it in preferences
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
 
# Displays the Preview and Changes tabs
$wgDefaultUserOptions['wikieditor-preview'] = 1;
 
# Displays the Publish and Cancel buttons on the top right side
$wgDefaultUserOptions['wikieditor-publish'] = 1;
 
# Displays a navigation column (summary) on the right side
$wgDefaultUserOptions['usenavigabletoc'] = 1;


# Language Extension Bundle
#$EXT = "$IP/extensions";
#require_once("$EXT/Babel/Babel.php");
#require_once("$EXT/cldr/cldr.php" );
#require_once("$EXT/CleanChanges/CleanChanges.php" );

#$wgCCTrailerFilter = true;
#$wgCCUserFilter = false;
#$wgDefaultUserOptions['usenewrc'] = 1;
 
#require_once("$EXT/LocalisationUpdate/LocalisationUpdate.php");
#$wgLocalisationUpdateDirectory = "$IP/cache";
#require_once( "$EXT/Translate/Translate.php" );
#$wgGroupPermissions['user']['translate'] = true;
#$wgGroupPermissions['user']['translate-messagereview'] = true;
#$wgGroupPermissions['user']['translate-groupreview'] = true;
#$wgGroupPermissions['user']['translate-import'] = true;
#$wgGroupPermissions['sysop']['pagetranslation'] = true;
#$wgGroupPermissions['sysop']['translate-manage'] = true;
#$wgTranslateDocumentationLanguageCode = 'qqq';

require_once( "$IP/extensions/UniversalLanguageSelector/UniversalLanguageSelector.php" );


$wgAllowImageTag = true;
#$wgEnableImageWhitelist =true;
$wgAllowExternalImages = true;

$wgGroupPermissions['*']['createaccount'] = false;

//Contact page
require_once( "$IP/extensions/ContactPage/ContactPage.php" );
$wgContactUser = 'Admin';
$wgContactSender = $wgPasswordSender;
$wgContactSenderName = 'Contact Form on ' . $wgSitename;

require_once( "$IP/skins/erudite/erudite.php" );

# Cite
require_once( "$IP/extensions/Cite/SpecialCite.php" );
$wgCiteEnablePopups = true;

# WYSIWYG
#require_once("$IP/extensions/WYSIWYG/WYSIWYG.php");
#$wgGroupPermissions['registered_users']['wysiwyg']=true;

# Category Tree
$wgUseAjax = true;

require_once( "$IP/extensions/CategoryTree/CategoryTree.php");
$wgCategoryTreeSidebarRoot = 'Introduction';
$wgCategoryTreeForceHeaders = true;

# Vector
require_once( "$IP/extensions/Vector/Vector.php" );
$wgVectorFeatures['collapsiblenav']['user'] = true;
$wgVectorFeatures['collapsiblenav']['global'] = true;

$wgVectorFeatures['collapsibletabs']['global'] = false;
$wgVectorFeatures['collapsibletabs']['user'] = true;

$wgVectorFeatures['sectioneditlinks']['global'] = true;
$wgVectorFeatures['sectioneditlinks']['user'] = true;

## Set upload limit
$wgMaxUploadSize = 1024*1024*200; # 200MB


## error 
#error_reporting( -1 );
#ini_set( 'display_errors', 1 );

## VE
#require_once("$IP/extensions/VisualEditor/VisualEditor.php");
 
// OPTIONAL: Enable VisualEditor in other namespaces
// By default, VE is only enabled in NS_MAIN
//$wgVisualEditorNamespaces[] = NS_PROJECT;
 
// Enable by default for everybody
#$wgDefaultUserOptions['visualeditor-enable'] = 1;
 
// Don't allow users to disable it
#$wgHiddenPrefs[] = 'visualeditor-enable';
 
// OPTIONAL: Enable VisualEditor's experimental code features
//$wgVisualEditorEnableExperimentalCode = true;

// URL to the Parsoid instance
// MUST NOT end in a slash due to Parsoid bug
#$wgVisualEditorParsoidURL = 'http://localhost:8000';
// Interwiki prefix to pass to the Parsoid instance
// Parsoid will be called as $url/$prefix/$pagename
#$wgVisualEditorParsoidPrefix = 'localhost';

$wgShowExceptionDetails = true;
require_once "$IP/extensions/LocalisationUpdate/LocalisationUpdate.php";
$wgLocalisationUpdateDirectory = "$IP/cache";

$wgDebugComments = true;

# Text Extract
require_once "$IP/extensions/TextExtracts/TextExtracts.php";
# Page Images
require_once "$IP/extensions/PageImages/PageImages.php";
# EventLogging
require_once "$IP/extensions/EventLogging/EventLogging.php";
$wgEventLoggingBaseUri = 'http://localhost:8080/event.gif';
$wgEventLoggingFile = '/var/log/mediawiki/events.log';

# Popups
require_once "$IP/extensions/Popups/Popups.php";

# Cite
require_once "$IP/extensions/Cite/Cite.php";

#Link_Attrubute
require_once "$IP/extensions/Link_Attributes/Link_Attributes.php";
$wgNoFollowLinks = false;
$wgExternalLinkTarget = '_blank';

